[package]
name = "vcd"
version = "0.2.0"
authors = ["Kevin Mehall <km@kevinmehall.net>"]
description = "Read and write VCD (Value Change Dump) files"
license = "MIT"
keywords = ["encoding", "parser", "vcd"]
repository = "https://github.com/kevinmehall/rust-vcd"
